In [1]:
import numpy as np
import sympy as sym

# Rotation

In [2]:
theta_x, theta_y = sym.symbols('theta_x, theta_y')

R_x = sym.Matrix([[1, 0, 0], [0, sym.cos(theta_x), -sym.sin(theta_x)], [0, sym.sin(theta_x), sym.cos(theta_x)]])
R_y = sym.Matrix([[sym.cos(theta_y), 0, sym.sin(theta_y)], [0, 1, 0], [-sym.sin(theta_y), 0, sym.cos(theta_y)]])

print('Rotation x-axis:')
display(R_x)
print('Rotation y-axis:')
display(R_y)

Rotation x-axis:


Matrix([
[1,            0,             0],
[0, cos(theta_x), -sin(theta_x)],
[0, sin(theta_x),  cos(theta_x)]])

Rotation y-axis:


Matrix([
[ cos(theta_y), 0, sin(theta_y)],
[            0, 1,            0],
[-sin(theta_y), 0, cos(theta_y)]])

In [3]:
print('Rotate x after y:')
display(R_x * R_y)

Rotate x after y:


Matrix([
[              cos(theta_y),            0,               sin(theta_y)],
[ sin(theta_x)*sin(theta_y), cos(theta_x), -sin(theta_x)*cos(theta_y)],
[-sin(theta_y)*cos(theta_x), sin(theta_x),  cos(theta_x)*cos(theta_y)]])

# FOV

In [43]:
fov = 90
t = np.tan(fov / 360 * np.pi)
print('t:')
display(t)
v = (0.5 / t) + 0.5
print('v:')
display(v)

t:


0.9999999999999999

v:


1.0

In [29]:
sprite_vertices = np.array([
    [0, 0],
    [1, 0],
    [1, 1],
    [0, 1],
])
sprite_vertices

array([[0, 0],
       [1, 0],
       [1, 1],
       [0, 1]])

In [30]:
sprite_vertices = sprite_vertices - 0.5
sprite_vertices

array([[-0.5, -0.5],
       [ 0.5, -0.5],
       [ 0.5,  0.5],
       [-0.5,  0.5]])

In [31]:
sprite_vertices = np.hstack((sprite_vertices, np.array([[0.5 / t]]*4)))
sprite_vertices

array([[-0.5, -0.5,  0.5],
       [ 0.5, -0.5,  0.5],
       [ 0.5,  0.5,  0.5],
       [-0.5,  0.5,  0.5]])

In [33]:
v = (0.5 / t) + 0.5
v

1.0